### PR TITLE
Regisration Page + Account Creation Page

### PR DESCRIPTION
**Pull request by atstojanov**
### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/cherrytwist/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Comment by techsmyth** [comment]
Really great to see this!

Just tried to run with the auth provider on a non-standard port (3003) - had updated the server config but seems that there is a redirect also within the client:
image
image

Will try further with hosting simple auth on the default port...

**Comment by atstojanov** [comment]
@techsmyth at this point the register endpoint is not configurable.

**Review by valentinyanakiev — COMMENTED** [review]
Code looks OK, but I still fail to be logged in when I do:
1. Register.
2. Log out.
3. Log in with the previously registered user.
image

**Review by techsmyth — APPROVED** [review]
Great to have this in. Merging so can generate an image with this in there for evaluating.

**Pull request merged**
