### PR TITLE
User information display to use Credentials

### PR DESCRIPTION
**Pull request by atstojanov**
### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/cherrytwist/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

### CODE REVIEW

**Review by techsmyth — CHANGES_REQUESTED** [review]
As per direct messages:
- assigning global admin says already a member
- list of assigned users does not refresh after assign / remove
- user profile page not showing membership

**Review by techsmyth — CHANGES_REQUESTED** [review]
The membership assignment is working fine now, thanks.

However the user info display on the panel is still saying cannot be resolved:
image

**Comment by atstojanov** [comment]
There is an update with example how community are resolved. Currently I don't have straight solution how to resolve user groups. Further discussion is required.

Removing the memberOf from user entity is bringing more complications than improvements.
Currently Getting all communities is required to be able to find to which one the user belongs to. For the groups is a bit harder.

**Comment by techsmyth** [comment]
> There is an update with example how community are resolved. Currently I don't have straight solution how to resolve user groups. Further discussion is required.
> 
> Removing the memberOf from user entity is bringing more complications than improvements.
> Currently getting all communities is required to be able to find to which one the user belongs to. For the groups is a bit harder.

Agreed that this should not be resolved on the client - see PR with a new membership service / query: https://github.com/cherrytwist/server/pull/972/files

**Review by techsmyth — APPROVED** [review]

**Pull request merged**
